controller_list:
  - name: fake_Manipulator_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_Local_Camera_controller
    joints:
      []